version: '3.0'
services:
    uploader:
        container_name: uploader
        image: dihri/com.dihri.microservices:latest
        ports:
            - 3333:3333
        networks:
            - cloud-network
        logging:
            driver: json-file
networks:
    cloud-network:
        driver: bridge
